import type { Env } from '../types';
import { queueApprovedTerminalGeneration } from './generation-run';
import {
  appendAgencyLog,
  checkStaleAgents,
  createAgentFinding,
  createAgentTask,
  createApprovedCommandJob,
  getAgencyClientCoverage,
  getPostByAutomationSlotKey,
  getAgentHealthSummary,
  getLatestAuditMarker,
  listAgentDefinitions,
  markAgentStale,
  resolveStaleFindings,
  updateAgentTask,
  writeAuditLog,
} from '../db/queries';
import { agencySafety, backendPriorityForAgent, commandForAgent } from '../modules/agency-contract';

// Weekend schedule — tasks run Friday night through Sunday.
// Mon–Thu: stale detection only, no job enqueueing.
// Orchestrator always runs daily after review agents so it can compile findings and notify Discord.
const DAILY_REVIEW_AGENTS = ['security-sentinel', 'system-reliability', 'agency-orchestrator'];

const SCHEDULE: Record<string, string[]> = {
  // Friday 10PM UTC — kick off the weekend sequence
  'fri-night':  [...DAILY_REVIEW_AGENTS, 'client-research'],
  // Saturday morning (UTC midnight–1PM) — research + strategy
  'sat-morning': ['client-research', 'strategy'],
  // Package content is generated by the canonical Sunday terminal run. These
  // specialist agents remain available on demand without competing for slots.
  'sat-afternoon': ['editorial-review'],
  'sun-morning': ['gmb-rank', 'editorial-review'],
  // Sunday afternoon (UTC 14+) — orchestrator wrap-up
  'sun-afternoon': ['agency-orchestrator'],
};

export interface AgencySchedulerStats {
  enabled: boolean;
  requested: string[];
  queued: number;
  skipped: number;
  stale_marked: string[];
  health_summary: Record<string, number>;
}

async function agencySchedulerEnabled(env: Env): Promise<boolean> {
  if (env.AGENCY_SCHEDULER_ENABLED === 'true') return true;
  try {
    const raw = await env.KV_BINDING.get('settings:system');
    const settings = raw ? JSON.parse(raw) as Record<string, string> : {};
    return settings['agency_scheduler_enabled'] === 'true';
  } catch {
    return false;
  }
}

export function weeklyGenerationPeriod(now: Date): { period_start: string; period_end: string } {
  const start = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  start.setUTCDate(start.getUTCDate() - start.getUTCDay());
  const end = new Date(start);
  end.setUTCDate(end.getUTCDate() + 6);
  return {
    period_start: start.toISOString().slice(0, 10),
    period_end: end.toISOString().slice(0, 10),
  };
}

function parseWeeklySchedule(raw: string | null): Record<string, string[]> {
  try {
    const parsed = JSON.parse(raw || '{}') as unknown;
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) return {};
    const out: Record<string, string[]> = {};
    for (const [day, value] of Object.entries(parsed as Record<string, unknown>)) {
      out[day.toLowerCase()] = Array.isArray(value) ? value.map((item) => String(item).toLowerCase()) : [];
    }
    return out;
  } catch {
    return {};
  }
}

function currentMonday(now: Date): string {
  const start = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  const diff = start.getUTCDay() === 0 ? 6 : start.getUTCDay() - 1;
  start.setUTCDate(start.getUTCDate() - diff);
  return start.toISOString().slice(0, 10);
}

function monthlyLimit(client: { images_per_month: number; videos_per_month: number; reels_per_month: number; blog_posts_per_month: number }, type: string): number {
  if (type === 'blog') return Number(client.blog_posts_per_month || 0);
  if (type === 'video') return Number(client.videos_per_month || 0);
  if (type === 'reel') return Number(client.reels_per_month || 0);
  return Number(client.images_per_month || 0);
}

function currentWeekPackageSlots(client: {
  client_id: string;
  weekly_schedule: string | null;
  images_per_month: number;
  videos_per_month: number;
  reels_per_month: number;
  blog_posts_per_month: number;
}, now: Date): Array<{ date: string; type: string; dailyIndex: number; slotKey: string }> {
  const schedule = parseWeeklySchedule(client.weekly_schedule);
  const monday = currentMonday(now);
  const weekDates = Array.from({ length: 7 }, (_, offset) => {
    const date = new Date(`${monday}T12:00:00Z`);
    date.setUTCDate(date.getUTCDate() + offset);
    return date.toISOString().slice(0, 10);
  });
  const monthUse: Record<string, Record<string, number>> = {};
  const slots: Array<{ date: string; type: string; dailyIndex: number; slotKey: string }> = [];
  for (const date of weekDates) {
    const day = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'][new Date(`${date}T12:00:00Z`).getUTCDay()]!;
    const month = date.slice(0, 7);
    monthUse[month] ??= {};
    const types = schedule[day] ?? [];
    for (const [dailyIndex, type] of types.entries()) {
      const limit = monthlyLimit(client, type);
      if (limit <= 0) continue;
      const next = (monthUse[month][type] ?? 0) + 1;
      if (next > limit) continue;
      monthUse[month][type] = next;
      slots.push({ date, type, dailyIndex, slotKey: `${client.client_id}:${date}:${type}:${dailyIndex}` });
    }
  }
  return slots;
}

export async function enqueueWeeklyPackageGeneration(
  env: Env,
  now = new Date(),
): Promise<{ queued: boolean; reason: string; run_id?: string; total_slots?: number }> {
  if (!(await agencySchedulerEnabled(env))) return { queued: false, reason: 'scheduler_disabled' };

  const period = weeklyGenerationPeriod(now);
  const dedupeKey = `${period.period_start}:${period.period_end}`;
  const previous = await getLatestAuditMarker(
    env.DB,
    'agency.scheduler.weekly_generation',
    'generation_period',
    dedupeKey,
  );
  if (previous) return { queued: false, reason: 'already_queued_this_week' };

  const queued = await queueApprovedTerminalGeneration(env, {
    client_slugs: [],
    period_start: period.period_start,
    period_end: period.period_end,
    triggered_by: 'agency_weekly_scheduler',
    publish_time: null,
    overwrite_existing: false,
    requested_in: 'weekly_cron',
  });
  await writeAuditLog(env.DB, {
    action: 'agency.scheduler.weekly_generation',
    entity_type: 'generation_period',
    entity_id: dedupeKey,
    new_value: {
      run_id: queued.run_id,
      job_id: queued.job_id,
      total_slots: queued.total_slots,
    },
  });
  return {
    queued: true,
    reason: 'queued',
    run_id: queued.run_id,
    total_slots: queued.total_slots,
  };
}

export async function enqueuePackageGapRecovery(
  env: Env,
  now = new Date(),
): Promise<{ queued: number; skipped: number; missing_slots: number; reason: string }> {
  if (!(await agencySchedulerEnabled(env))) return { queued: 0, skipped: 0, missing_slots: 0, reason: 'scheduler_disabled' };

  const coverage = await getAgencyClientCoverage(env.DB);
  const agents = await listAgentDefinitions(env.DB);
  let queued = 0;
  let skipped = 0;
  let missingSlots = 0;
  const weekStart = currentMonday(now);

  for (const client of coverage) {
    const slots = currentWeekPackageSlots(client, now);
    for (const slot of slots) {
      const existing = await getPostByAutomationSlotKey(env.DB, client.client_id, slot.slotKey);
      if (existing && existing.status !== 'cancelled') {
        skipped++;
        continue;
      }

      missingSlots++;
      const agentSlug = slot.type === 'blog' ? 'blog-writer' : 'social-copy';
      const commandName = commandForAgent(agentSlug);
      const agent = agents.find((item) => item.slug === agentSlug);
      if (!agent || agent.enabled !== 1 || !commandName) {
        skipped++;
        continue;
      }

      const dedupeKey = `${weekStart}:${client.client_id}:${slot.slotKey}`;
      const previous = await getLatestAuditMarker(env.DB, 'agency.scheduler.gap_recovery', 'package_slot', dedupeKey);
      if (previous) {
        skipped++;
        continue;
      }

      const task = await createAgentTask(env.DB, {
        agent_slug: agentSlug,
        client_id: client.client_id,
        title: `Recover missing ${slot.type} package slot for ${client.client_name}`,
        priority: 'high',
        input_json: JSON.stringify({
          requested_from: 'daily_package_gap_recovery',
          mode: 'recover_missing_slots',
          week_start: weekStart,
          client_id: client.client_id,
          client_slug: client.client_slug,
          missing_slots: [slot],
        }),
      });
      const job = await createApprovedCommandJob(env.DB, {
        generation_run_id: null,
        command_name: commandName,
        provider: agent.default_backend,
        requested_by: 'daily_package_gap_recovery',
        args_json: JSON.stringify({
          agent_slug: agentSlug,
          task_id: task.id,
          source: 'daily_package_gap_recovery',
          mode: 'recover_missing_slots',
          week_start: weekStart,
          client_id: client.client_id,
          client_slug: client.client_slug,
          missing_slots: [slot],
          backend_priority: backendPriorityForAgent(agentSlug),
          safety: agencySafety(),
        }),
      });
      await updateAgentTask(env.DB, task.id, { approved_job_id: job.id, status: 'queued', progress: 0 });
      await appendAgencyLog(env.DB, {
        agent_slug: agentSlug,
        task_id: task.id,
        job_id: job.id,
        status: 'queued',
        step: 'package_gap_recovery',
        summary: `${agent.name} queued to recover ${client.client_name} ${slot.date} ${slot.type} package slot.`,
        backend: agent.default_backend,
      });
      await writeAuditLog(env.DB, {
        action: 'agency.scheduler.gap_recovery',
        entity_type: 'package_slot',
        entity_id: dedupeKey,
        new_value: { agent_slug: agentSlug, command_name: commandName, job_id: job.id, slot },
      });
      queued++;
    }
  }

  return { queued, skipped, missing_slots: missingSlots, reason: queued > 0 ? 'queued' : 'no_missing_slots' };
}

function requestedAgents(now: Date): string[] {
  const day  = now.getUTCDay();   // 0=Sun 1=Mon … 5=Fri 6=Sat
  const hour = now.getUTCHours();

  if (day === 5 && hour >= 20) return SCHEDULE['fri-night']!;      // Fri 8PM+
  if (day === 6 && hour < 14)  return SCHEDULE['sat-morning']!;    // Sat AM
  if (day === 6 && hour >= 14) return SCHEDULE['sat-afternoon']!;  // Sat PM
  if (day === 0 && hour < 14)  return SCHEDULE['sun-morning']!;    // Sun AM
  if (day === 0 && hour >= 14) return SCHEDULE['sun-afternoon']!;  // Sun PM

  // Mon–Thu: security + system review + orchestrator report runs daily
  return DAILY_REVIEW_AGENTS;
}

/**
 * Detect agents whose heartbeat window has elapsed, mark them stale, record a
 * finding + log line, and return the slugs marked. Centralized so both the
 * weekend scheduler and the per-minute cron use identical logic.
 */
export async function runAgentStaleSweep(env: Env): Promise<string[]> {
  // Auto-close findings not re-detected in 7 days so the dashboard reflects
  // current state, not historical/already-fixed evidence. Persistent issues are
  // re-raised by the next agent run.
  await resolveStaleFindings(env.DB, 7).catch(() => 0);
  const staleAgents = await checkStaleAgents(env.DB);
  const stale_marked: string[] = [];
  for (const agent of staleAgents) {
    const msg = `Missed heartbeat window (${agent.stale_after_minutes}m)`;
    await markAgentStale(env.DB, agent.slug, msg);
    await createAgentFinding(env.DB, {
      agent_slug: agent.slug,
      task_id: null,
      client_id: null,
      severity: 'medium',
      title: `${agent.name} is stale`,
      finding_json: JSON.stringify({
        last_heartbeat_at: agent.last_heartbeat_at,
        stale_after_minutes: agent.stale_after_minutes,
        previous_status: agent.heartbeat_status,
      }),
    });
    await appendAgencyLog(env.DB, {
      agent_slug: agent.slug,
      task_id: null,
      status: 'stale',
      step: 'stale_check',
      summary: `${agent.name} marked stale — ${msg}`,
    });
    stale_marked.push(agent.slug);
  }
  return stale_marked;
}

export async function runAgencyScheduler(env: Env, now = new Date()): Promise<AgencySchedulerStats> {
  const requested = requestedAgents(now);
  const enabled = await agencySchedulerEnabled(env);
  if (!enabled) {
    const stale_marked = await runAgentStaleSweep(env);
    const health_summary = await getAgentHealthSummary(env.DB);
    return { enabled, requested, queued: 0, skipped: requested.length, stale_marked, health_summary };
  }

  const agents = await listAgentDefinitions(env.DB);
  let queued = 0;
  let skipped = 0;
  const dayKey = now.toISOString().slice(0, 10);

  for (const agentSlug of requested) {
    const agent = agents.find((item) => item.slug === agentSlug);
    const commandName = commandForAgent(agentSlug);
    if (!agent || agent.enabled !== 1 || !commandName) {
      skipped++;
      continue;
    }

    const dedupeKey = `${dayKey}:${agentSlug}`;
    const previous = await getLatestAuditMarker(env.DB, 'agency.scheduler.enqueue', 'agent_schedule', dedupeKey);
    if (previous) {
      skipped++;
      continue;
    }

    const task = await createAgentTask(env.DB, {
      agent_slug: agentSlug,
      title: `Scheduled ${agent.name} run`,
      input_json: JSON.stringify({ requested_from: 'agency_scheduler', day_key: dayKey }),
    });
    const job = await createApprovedCommandJob(env.DB, {
      generation_run_id: null,
      command_name: commandName,
      provider: agent.default_backend,
      requested_by: 'agency_scheduler',
      args_json: JSON.stringify({
        agent_slug: agentSlug,
        task_id: task.id,
        source: 'agency_scheduler',
        day_key: dayKey,
        backend_priority: backendPriorityForAgent(agentSlug),
        safety: agencySafety(),
      }),
    });
    await updateAgentTask(env.DB, task.id, { approved_job_id: job.id, status: 'queued', progress: 0 });
    await appendAgencyLog(env.DB, {
      agent_slug: agentSlug,
      task_id: task.id,
      job_id: job.id,
      status: 'queued',
      step: 'scheduler',
      summary: `${agent.name} queued by agency scheduler.`,
      backend: agent.default_backend,
    });
    await writeAuditLog(env.DB, {
      action: 'agency.scheduler.enqueue',
      entity_type: 'agent_schedule',
      entity_id: dedupeKey,
      new_value: { agent_slug: agentSlug, command_name: commandName, job_id: job.id },
    });
    queued++;
  }

  // Stale detection — runs every cron tick regardless of scheduler enabled flag
  const stale_marked = await runAgentStaleSweep(env);

  const health_summary = await getAgentHealthSummary(env.DB);

  return { enabled, requested, queued, skipped, stale_marked, health_summary };
}

/**
 * Enqueue a single editorial-review pass. Used by the business-hours editorial
 * cron so freshly generated content (manual or scheduled) gets reviewed within
 * hours instead of waiting for the weekend sweep, landing it in Marvin's
 * approval queue faster. Dedupe is hour-scoped (not the per-day key used by the
 * main scheduler) so it can run multiple times a day. Review only — never
 * approves (Marvin gate) or delivers assets (designer gate) stay intact.
 */
export async function enqueueEditorialSweep(env: Env, now = new Date()): Promise<{ queued: boolean; reason: string }> {
  if (!(await agencySchedulerEnabled(env))) return { queued: false, reason: 'scheduler_disabled' };

  const agentSlug = 'editorial-review';
  const commandName = commandForAgent(agentSlug);
  const agents = await listAgentDefinitions(env.DB);
  const agent = agents.find((item) => item.slug === agentSlug);
  if (!agent || agent.enabled !== 1 || !commandName) return { queued: false, reason: 'agent_unavailable' };

  const dayKey = now.toISOString().slice(0, 10);
  // Hour-scoped dedupe so retries/duplicate cron fires in the same hour are no-ops
  // but each 3-hour business-hours tick still enqueues its own pass.
  const hourKey = `${dayKey}:H${String(now.getUTCHours()).padStart(2, '0')}:${agentSlug}`;
  const previous = await getLatestAuditMarker(env.DB, 'agency.scheduler.enqueue', 'agent_schedule', hourKey);
  if (previous) return { queued: false, reason: 'already_queued_this_hour' };

  const task = await createAgentTask(env.DB, {
    agent_slug: agentSlug,
    title: 'Business-hours editorial review',
    input_json: JSON.stringify({ requested_from: 'agency_editorial_sweep', day_key: dayKey }),
  });
  const job = await createApprovedCommandJob(env.DB, {
    generation_run_id: null,
    command_name: commandName,
    provider: agent.default_backend,
    requested_by: 'agency_editorial_sweep',
    args_json: JSON.stringify({
      agent_slug: agentSlug,
      task_id: task.id,
      source: 'agency_editorial_sweep',
      day_key: dayKey,
      backend_priority: backendPriorityForAgent(agentSlug),
      safety: agencySafety(),
    }),
  });
  await updateAgentTask(env.DB, task.id, { approved_job_id: job.id, status: 'queued', progress: 0 });
  await appendAgencyLog(env.DB, {
    agent_slug: agentSlug,
    task_id: task.id,
    job_id: job.id,
    status: 'queued',
    step: 'editorial_sweep',
    summary: `${agent.name} queued by business-hours editorial sweep.`,
    backend: agent.default_backend,
  });
  await writeAuditLog(env.DB, {
    action: 'agency.scheduler.enqueue',
    entity_type: 'agent_schedule',
    entity_id: hourKey,
    new_value: { agent_slug: agentSlug, command_name: commandName, job_id: job.id },
  });
  return { queued: true, reason: 'queued' };
}
