/**
 * One-time migration: ACCOUNTS_MAP.json → D1
 *
 * Run:
 *   npx tsx scripts/migrate-accounts-map.ts
 *
 * This generates a SQL file at db/migrations/0002_accounts_map_seed.sql
 * then apply with: wrangler d1 execute webxni-db --file=db/migrations/0002_accounts_map_seed.sql
 */

import * as fs from 'fs';
import * as path from 'path';

const ACCOUNTS_MAP_PATH =
  '/home/marvinesu/.openclaw/workspace/skills/upload-post/ACCOUNTS_MAP.json';
const WP_CLIENTS_PATH =
  '/home/marvinesu/.openclaw/workspace/skills/wordpress-pro/WP_CLIENTS.json';
const OUT_PATH = path.join(__dirname, '../db/migrations/0002_accounts_map_seed.sql');

// ─────────────────────────────────────────────────────────────────────────────
// helpers
// ─────────────────────────────────────────────────────────────────────────────
function q(v: unknown): string {
  if (v === null || v === undefined) return 'NULL';
  const s = String(v).replace(/'/g, "''");
  return `'${s}'`;
}
function id(): string {
  return Math.random().toString(16).slice(2) + Math.random().toString(16).slice(2);
}
const now = Math.floor(Date.now() / 1000);

// ─────────────────────────────────────────────────────────────────────────────
// load source files
// ─────────────────────────────────────────────────────────────────────────────
const accountsMap = JSON.parse(fs.readFileSync(ACCOUNTS_MAP_PATH, 'utf8'));
const wpClients = JSON.parse(fs.readFileSync(WP_CLIENTS_PATH, 'utf8'));
const clients = accountsMap.clients as Record<string, Record<string, unknown>>;
const wpClientMap = wpClients.clients as Record<string, Record<string, unknown>>;

const lines: string[] = [];
lines.push('-- Generated by migrate-accounts-map.ts');
lines.push('-- DO NOT EDIT MANUALLY\n');

// ─────────────────────────────────────────────────────────────────────────────
// clients table
// ─────────────────────────────────────────────────────────────────────────────
const clientIdMap: Record<string, string> = {};

for (const [slug, cfg] of Object.entries(clients)) {
  const clientId = id();
  clientIdMap[slug] = clientId;

  const rules = (cfg['posting_rules'] as Record<string, unknown>) ?? {};
  const wp = wpClientMap[slug] ?? {};
  const brand = (wp['brand'] as Record<string, unknown>) ?? {};
  const brandJson = Object.keys(brand).length > 0 ? JSON.stringify(brand) : null;

  // never_mix_with array → JSON string
  const neverMix = rules['never_mix_with']
    ? JSON.stringify(rules['never_mix_with'])
    : null;

  lines.push(`INSERT OR IGNORE INTO clients
  (id, slug, canonical_name, package, status, owner_group, manual_only,
   requires_approval_from, language, never_mix_with, upload_post_profile,
   wp_domain, wp_url, wp_auth, wp_template, brand_json, notes, created_at, updated_at)
VALUES (
  ${q(clientId)}, ${q(slug)}, ${q(cfg['canonical_name'])},
  'medium', 'active',
  ${q(rules['owner_group'] ?? null)},
  ${rules['manual_only'] ? 1 : 0},
  ${q(rules['requires_approval_from'] ?? null)},
  ${q(cfg['language'] ?? 'en')},
  ${q(neverMix)},
  ${q(cfg['upload_post_profile'] ?? null)},
  ${q(wp['domain'] ?? null)},
  ${q(wp['wp_url'] ?? null)},
  ${q(wp['auth'] ?? null)},
  ${q(wp['template'] ?? null)},
  ${q(brandJson)},
  ${q((rules['notes'] as string) ?? null)},
  ${now}, ${now}
);\n`);

  // ── content restrictions ──────────────────────────────────────────────────
  const restrictions = (rules['content_restrictions'] as string[]) ?? [];
  for (const term of restrictions) {
    lines.push(
      `INSERT OR IGNORE INTO client_restrictions (client_id, term) VALUES (${q(clientId)}, ${q(term)});`,
    );
  }
  if (restrictions.length) lines.push('');

  // ── platforms ─────────────────────────────────────────────────────────────
  const platforms = (cfg['platforms'] as Record<string, Record<string, unknown>>) ?? {};
  for (const [platform, platCfg] of Object.entries(platforms)) {
    if (platform === 'google_business' && platCfg['gbp_locations']) {
      // Multi-location GBP — insert main platform row + location rows
      const mainPlatId = id();
      lines.push(`INSERT OR IGNORE INTO client_platforms
  (id, client_id, platform, account_id, upload_post_location_id, paused, notes)
VALUES (
  ${q(mainPlatId)}, ${q(clientId)}, 'google_business',
  NULL,
  ${q(platCfg['upload_post_location_id'] ?? null)},
  0, ${q(platCfg['note'] ?? null)}
);\n`);

      const locations = platCfg['gbp_locations'] as Array<Record<string, unknown>>;
      for (let i = 0; i < locations.length; i++) {
        const loc = locations[i];
        lines.push(`INSERT OR IGNORE INTO client_gbp_locations
  (id, client_id, label, location_id, upload_post_profile, caption_field, posted_field, paused, paused_reason, sort_order)
VALUES (
  ${q(id())}, ${q(clientId)}, ${q(loc['label'])}, ${q(loc['location_id'])},
  ${q(loc['profile'] ?? cfg['upload_post_profile'] ?? null)},
  ${q(loc['caption_field'] ?? null)},
  ${q(loc['posted_field'] ?? null)},
  ${loc['paused'] ? 1 : 0},
  ${q(loc['paused_reason'] ?? null)},
  ${i}
);\n`);
      }
      continue;
    }

    const platId = id();
    const paused = platCfg['paused'] ? 1 : 0;

    lines.push(`INSERT OR IGNORE INTO client_platforms
  (id, client_id, platform, account_id, username, page_id,
   upload_post_board_id, upload_post_location_id,
   privacy_level, privacy_status, paused, paused_reason, paused_since, notes)
VALUES (
  ${q(platId)}, ${q(clientId)}, ${q(platform)},
  ${q(platCfg['account_id'] ?? null)},
  ${q(platCfg['username'] ?? platCfg['fullname'] ?? null)},
  ${q(platCfg['page_id'] ?? null)},
  ${q(platCfg['upload_post_board_id'] ?? platCfg['board_id'] ?? null)},
  ${q(platCfg['upload_post_location_id'] ?? null)},
  ${q(platCfg['privacy_level'] ?? null)},
  ${q(platCfg['privacy_status'] ?? null)},
  ${paused},
  ${q(platCfg['paused_reason'] ?? null)},
  ${q(platCfg['paused_since'] ?? null)},
  ${q(platCfg['upload_post_note'] ?? platCfg['note'] ?? null)}
);\n`);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// write output
// ─────────────────────────────────────────────────────────────────────────────
const output = lines.join('\n');
fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
fs.writeFileSync(OUT_PATH, output, 'utf8');

console.log(`✅ Written to ${OUT_PATH}`);
console.log(`   ${Object.keys(clients).length} clients`);
console.log(`\nApply with:`);
console.log(`  wrangler d1 execute webxni-db --file=db/migrations/0002_accounts_map_seed.sql`);
